version: "3"
services:
  ecodms-ecodms21-12:
    command:
      - /opt/ecodms/ecodmsserver/run.sh
    container_name: ecodms-ecodms21-12
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=eng
      - LANGUAGE=eng
      - LC_ALL=de_DE.UTF-8
    hostname: ecodms-ecodms21
    image: ecodms/ecodms:21.12-01
    ipc: private
    logging:
      driver: db
      options: {}
    ports:
      - 17001:17001/tcp
      - 17002:17002/tcp
      - 8080:8080/tcp
      - 8180:8180/tcp
    restart: always
    stdin_open: true
    tty: true
    user: root
    volumes:
      - /volume1/Public/Scan/ScanInput:/srv/scaninput:rw
      - /volume1/docker/ecoDMS21.12:/srv/data:rw
      - /volume1/ecoDMS/Restore:/srv/restore:rw
      - /volume1/ecoDMS/Backup:/srv/backup:rw
networks: {}
